# Generated by Django 5.2.5 on 2026-04-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='Fashion Bootique Noir', max_length=120)),
                ('brand_tagline', models.CharField(default='For women without limits', max_length=180)),
                ('footer_description', models.TextField(default='A premium dark-mode concept for clients who want stronger contrast, couture energy, and a bold luxury storefront.')),
                ('hero_eyebrow', models.CharField(default='Couture bridal edits and bold event dressing', max_length=120)),
                ('hero_heading', models.CharField(default='Luxury-focused looks for clients who want the boutique to feel unforgettable.', max_length=220)),
                ('trust_eyebrow', models.CharField(default='Luxury reassurance', max_length=120)),
                ('trust_heading', models.CharField(default='Premium buying signals that make a bold brand feel trustworthy from the first scroll.', max_length=220)),
                ('testimonial_eyebrow', models.CharField(default='Spotlight reviews', max_length=120)),
                ('testimonial_heading', models.CharField(default='A bold concept that feels premium, editorial, and instantly memorable.', max_length=220)),
                ('contact_heading', models.CharField(default='Talk to the boutique team for orders, customisation, and delivery updates.', max_length=220)),
                ('cta_eyebrow', models.CharField(default='Private styling desk', max_length=120)),
                ('cta_heading', models.CharField(default='Offer a concierge-style WhatsApp consultation for VIP picks, fittings, and urgent occasion orders.', max_length=220)),
                ('contact_location', models.CharField(default='Eros Sampoornam, Noida Extension', max_length=180)),
                ('contact_map_link', models.URLField(default='https://maps.google.com/?q=Eros+Sampoornam+Noida+Extension')),
                ('contact_phone', models.CharField(default='+91 92112 61727', max_length=30)),
                ('contact_hours', models.CharField(default='Support on WhatsApp, Monday to Saturday', max_length=180)),
                ('contact_email', models.EmailField(default='hello@bootique-demo.com', max_length=254)),
            ],
        ),
    ]
